### ISSUE TITLE
Sanity Test javascript PMV Code from CBE Comfort Tool

### ISSUE THREAD

**Issue by carlosparadis** [erdl/thermal_comfort#1]
Eileen requested PMV scores to be calculated for some sample data so we can sanity test the code, given strange results for Illima, KWest, and KWEast exceeding over -7 PMV on last report.

**Comment by kathrynparadis** [comment]
After testing the current PMV script on the simulation data from Riley, we found that the resulting PMV numbers are low (-3.7) in comparison to the CBE online tool (-0.9) whenever we used a clothing level less than 1.

![troubleshoot_pmv](https://user-images.githubusercontent.com/30536250/39162038-40618ef8-470f-11e8-896c-00011e50cb4c.png)

![troubleshoot_pmv_cbe](https://user-images.githubusercontent.com/30536250/39162056-5cf2156a-470f-11e8-9a17-2c46376c2474.png)
